### ISSUE TITLE
Strange get_collector() behavior

### ISSUE THREAD

**Issue by jwcraftsman** [igordejanovic/parglare#54]
parglare version: 0.6.1
Python version: Python 2.7.6
Operating System: Ubuntu 14.04

When running this program with Python 2:

```
from parglare import get_collector

action = get_collector()

def f(context, node):
    return node

action('f_action')(f)
```
An error occurs:

```
Traceback (most recent call last):
  File "test_unicode.py", line 9, in <module>
    action('f_action')(f)
  File "parglare/parglare/common.py", line 153, in __call__
    return decorator(name_or_f)
  File "parglare/parglare/common.py", line 140, in decorator
    name = f.__name__
AttributeError: 'str' object has no attribute '__name__'
```
The error goes away when add this line to the top of the file:

```
from __future__ import unicode_literals
```

The error does not occur when I run the original program with Python 3.4.0.

**Comment by igordejanovic** [comment]
Fixed on `master`. Please test.

**Comment by jwcraftsman** [comment]
Works for me.  Thanks!
