### ISSUE TITLE
Can't use dot as a terminal

### ISSUE THREAD

**Issue by SupraSummus** [igordejanovic/parglare#69]
* parglare version: rev ef27e8813455a9b26fb8af71a0d8a7f0d286f793
* Python version: 3.7
* Operating System: linux x64

### Description

`Grammar.from_string` forbids to use dot (`.`) as a terminal inlined in rule. If this is intentional then the error message seems misleading (`Using dot in names is not allowed.`)

### What I Did

```
>>> import parglare
>>> parglare.Grammar.from_string('a: ".";')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/programowanie/parglare/parglare/grammar.py", line 1111, in from_string
    return Grammar._parse('parse', grammar_str, **kwargs)
  File "/home/jan/programowanie/parglare/parglare/grammar.py", line 1094, in _parse
    context=context)
  File "/home/jan/programowanie/parglare/parglare/parser.py", line 299, in parse
    result = self._call_reduce_action(context, subresults)
  File "/home/jan/programowanie/parglare/parglare/parser.py", line 646, in _call_reduce_action
    subresults)
  File "/home/jan/programowanie/parglare/parglare/grammar.py", line 1815, in act_gsymbol_string_recognizer
    check_name(context, terminal_ref.name)
  File "/home/jan/programowanie/parglare/parglare/grammar.py", line 1265, in check_name
    message='Using dot in names is not allowed.'.format(name))
parglare.exceptions.GrammarError: Error at 1:3:"a: *".";" => Using dot in names is not allowed.
```

**Comment by igordejanovic** [comment]
Thanks for reporting. Literal string matches in the grammar are converted to terminals where name of the terminals equals the content of the match (dot in this case). Dot has a special [semantic in names](http://www.igordejanovic.net/parglare/latest/grammar_modularization/). It is used for FQN in the context of grammar imports. I think that a note in the docs should be added and maybe the error message should be extended to warn about this.

**Comment by SupraSummus** [comment]
Thanks for explaining mechanism of this behavior.

I may open a PR improving this. What do you think about escaping automatic terminal names? For example `.` -> `__dot__`

**Comment by igordejanovic** [comment]
Yup, that should be ok.

**Comment by stuartlangridge** [comment]
I've worked around this with a terminal `DOT: ".";` and then using it in grammar rules with `Sentence: Word* DOT;` which is not ideal but has helped me make progress at least.
