### ISSUE TITLE
Parse errors contain unescaped characters

### ISSUE THREAD

**Issue by SupraSummus** [igordejanovic/parglare#71]
* parglare version: rev ef27e8813455a9b26fb8af71a0d8a7f0d286f793
* Python version: 3.7
* Operating System: linux x86_64

### Description

Raised parse errors contain unescaped characters. It may result in unreadable error messages (from what I tested `\r` wrecks havoc).

### What I Did

```python
import parglare

grammar = parglare.Grammar.from_string('s: "a";')
parser = parglare.Parser(grammar)
parser.parse("\r")
```

Output of above program is (and I suspect it depends on shell used, but it shows the problem).
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(parser.parse("\r"))
  File "/home/jan/programowanie/parglare/parglare/parser.py", line 204, in parse
    raise error
*" => Expected: ans.ParseError: Error at 1:1:"
```

**Comment by igordejanovic** [comment]
Looks like a bug. Thanks for reporting.
