### ISSUE TITLE
Parser construction success depends on alternatives order

### ISSUE THREAD

**Issue by SupraSummus** [igordejanovic/parglare#73]
* parglare version: rev ef27e8813455a9b26fb8af71a0d8a7f0d286f793
* Python version: 3.7
* Operating System: linux 4.18.16 x86_64

### Description

Parser construction fails for grammar
```
s: as EOF;
as: as "a" | EMPTY;
```

however it succeeds for
```
s: as EOF;
as: EMPTY | as "a";
```
Issue affects also GLR parser.

### What I Did

```
from parglare import Parser, Grammar

grammar = r"""
s: as EOF;
as: as "a" | EMPTY;
"""

g = Grammar.from_string(grammar)
parser = Parser(g)
```
stacktrace:
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    parser = Parser(g)
  File "/home/jan/programowanie/parglare/parglare/parser.py", line 86, in __init__
    in_layout=self.in_layout)
  File "/home/jan/programowanie/parglare/parglare/tables/__init__.py", line 83, in create_load_table
    prefer_shifts, prefer_shifts_over_empty)
  File "/home/jan/programowanie/parglare/parglare/tables/__init__.py", line 120, in create_table
    'grammar symbol.'.format(nt))
parglare.exceptions.GrammarError: Error at 2:0:"\n*s: as EOF;" => First set empty for grammar symbol "s". An infinite recursion on the grammar symbol.
```

**Comment by igordejanovic** [comment]
Thanks. An edge case but a serious one. Parser construction should not depend in any way on the alternative ordering.
