### ISSUE TITLE
Parser rejects proper input

### ISSUE THREAD

**Issue by SupraSummus** [igordejanovic/parglare#84]
* parglare version: 1e2719378983fb069d5c50645143235f037afb85
* Python version: 3.7
* Operating System: linux x86_64 4.18.16

### Description

I get parse errors on a string that should be parsed successfully. Details below.

### What I Did

```python
from parglare import Grammar, GLRParser

g = Grammar.from_string("""
expression: "1" s letter EOF
          | "2" s "A" EOF
          ;

s: " ";

terminals
letter: /[A-Z]/;

""")

p = GLRParser(g, ws='')

p.parse("2 A")
p.parse("1 B")
p.parse("1 A")
```
last line throws:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    p.parse("1 A")
  File "/home/jan/programowanie/parglare/parglare/glr.py", line 185, in parse
    for h in last_heads_for_reduce}))
parglare.exceptions.ParseError: Error at 1:2:"1 *A" => Expected: letter but found <A(A)> or <letter(A)>
```

**Comment by SupraSummus** [comment]
My short investigation revealed that this is caused by `finish_flag` being automatically set for  terminals during table construction (in `LRTable.calc_finish_flags()`). With this part disabled the example I provided above is successful. However the code can't be simply commented out, because grammar parsing depends on it.

And this leads to another observation:
```python
from parglare import Grammar, Parser

g = Grammar.from_string("""
s: "a" EOF | letter EOF;

terminals
letter: /[a-z]/;
""")
p = Parser(g, actions={
    's': [
        lambda _, c: 'a',
        lambda _, c: 'letter',
    ],
})
print(p.parse('a'))
```

Above code parses input ok (as an `a`), but I wonder if it should raise an error telling that there is terminal conflict/ambiguity?

**Comment by igordejanovic** [comment]
I forgot to mention [custom lexical disambiguation and token recognition](http://www.igordejanovic.net/parglare/latest/disambiguation/#custom-token-recognition-and-lexical-disambiguation). With a slight change in the `_next_token` method user could be given a full control over implicit disambiguation by not calling `_lexical_disambiguation` in case of `custom_token_recognition` but making it part of the public API and documenting it and letting user call it if needed from `custom_token_recognition`. A parser flag for disabling implicit lexical disambiguation could just attach a built-in function to `custom_token_recognition` that will take care of things.

Another note on `_token_recognition` -- it is using a short-circuiting by presorting recognizers by priority and specificity. It is an optimization measure that gives a significant speedup and implements part of the implicit disambiguation strategy.
